import { readFileSync } from 'node:fs';
import assert from 'node:assert/strict';

const src = readFileSync(new URL('../src/main.jsx', import.meta.url), 'utf8');

assert.match(src, /View Logs/, 'header includes View Logs label');
assert.match(src, /window\.open\('\/logs', '_blank', 'noopener,noreferrer'\)/, 'View Logs opens /logs in a safe new tab');
assert.match(src, /function LogsPage\(/, 'dedicated LogsPage exists');
assert.match(src, /new EventSource\(`\$\{API\}\/system\/logs\/stream/, 'logs page connects to SSE endpoint');
assert.match(src, /All containers/, 'logs page has all containers option');
assert.match(src, /Pause/, 'logs page has pause control');
assert.match(src, /Auto-scroll/, 'logs page has auto-scroll control');
assert.match(src, /Copy visible logs/, 'logs page has copy control');
assert.match(src, /Download/, 'logs page has download control');
assert.match(src, /slice\(-bufferLimit\)/, 'maximum frontend buffer is enforced');
assert.match(src, /highlight\(/, 'search highlighting is wired');
assert.doesNotMatch(src, /dangerouslySetInnerHTML/, 'logs are not rendered with dangerouslySetInnerHTML');
assert.match(src, /function TargetLoadingScreen\(/, 'target loading screen exists');
assert.match(src, /setLoadingTarget\(t\)[\s\S]*targets\/\$\{t\.id\}\/results/, 'target results load only after the loading state is shown');
assert.match(src, /Other targets remain unloaded/, 'loading screen explains lazy target loading');
assert.match(src, /use_subdomains_top1million_110000: false/, 'top 110k DNS brute-force list is disabled by default');
assert.match(src, /use_bug_bounty_subdomains_trickest: false/, 'Trickest DNS brute-force list is disabled by default');
assert.match(src, /Use subdomains-top1million-110000\.txt/, 'scan settings include top 110k DNS brute-force checkbox');
assert.match(src, /Use bug-bounty-program-subdomains-trickest-inventory\.txt/, 'scan settings include Trickest DNS brute-force checkbox');
assert.match(src, /use_cached_subdomains: true/, 'subdomain cache is enabled by default');
assert.match(src, /refresh_passive_subdomains: true/, 'passive refresh remains enabled by default');
assert.match(src, /fresh_subdomain_scan: false/, 'fresh-only scans are disabled by default');
assert.match(src, /subfinder_recursive: false/, 'Subfinder recursive mode is disabled by default');
assert.match(src, /use_crtsh: false/, 'crt.sh passive source is disabled by default');
assert.match(src, /Use saved subdomains for this target/, 'scan settings include saved subdomain cache checkbox');
assert.match(src, /Refresh passive sources now/, 'scan settings include passive refresh checkbox');
assert.match(src, /Fresh scan only, ignore saved subdomains/, 'scan settings include fresh-only checkbox');
assert.match(src, /Clear subdomain cache for this target/, 'scan settings include clear subdomain cache action');
assert.match(src, /Use Subfinder recursive mode/, 'scan settings include optional Subfinder recursive toggle');
assert.match(src, /Use crt\.sh certificate transparency/, 'scan settings include optional crt.sh toggle');
assert.match(src, /'JS Intel'/, 'JS Intel has its own top-level page tab');
assert.match(src, /run_js_intel: true/, 'JS Intel remains present in default scan options');
assert.match(src, /JavaScript \+ TruffleHog/, 'scan settings include mandatory JS bundle and TruffleHog scanning');
assert.match(src, /Always on/, 'JS Intel is presented as always-on');
assert.match(src, /trufflehog_results: 'verified,unknown,unverified'/, 'TruffleHog scans verified, unknown, and unverified results by default');
assert.match(src, /source-sink|source→sink|source → sink/i, 'JS Intel settings explain source-sink detection');
assert.match(src, /js_findings/, 'frontend consumes JS Intel findings from the API');
assert.match(src, /'Arjun'/, 'Arjun has its own top-level page tab');
assert.match(src, /\/scans\/\$\{parentScanId\}\/arjun/, 'manual Arjun action calls the dedicated Arjun endpoint');
assert.match(src, /Arjun Options/, 'scan settings include separate Arjun options');
assert.match(src, /Arjun Results/, 'Arjun page includes a dedicated results section');
assert.match(src, /Run Arjun on selected URLs/, 'Arjun page includes manual selected-URL Arjun action');
assert.doesNotMatch(src, /Run Arjun after parameter discovery/, 'Arjun is not offered as an automatic scan-pipeline option');
assert.match(src, /source_url \|\| r\.base_url/, 'manual Arjun action uses parameter source URLs');
assert.match(src, /r\.url \|\| r\.source_url \|\| r\.name/, 'copy selected includes parameter source URLs');
assert.match(src, /Stop scan/, 'header includes stop scan action while a scan is active');
assert.match(src, /\/scans\/\$\{scanId\}\/stop/, 'stop scan action calls the stop endpoint');
assert.match(src, /\['queued', 'running', 'stopping'\]/, 'polling and disabled states include stopping scans');

console.log('frontend log viewer static tests passed');
